name: Deploy to Function on Release

on:
  release:
    types: [published]

env:
  NAME: func-tci-services
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DB_HOST: ${{ secrets.TCI_MDB_HOST }}
  DB_USER: ${{ secrets.TCI_MDB_USER }}
  DB_PASSWORD: ${{ secrets.TCI_MDB_PASSWORD }}
  DB_NAME: ${{ secrets.TCI_MDB_NAME }}

jobs:
  build_save:
    uses: IATI/.github/.github/workflows/build_node_save.yaml@main
    with:
      save_artifact: true
      artifact_name: build-artifact

  deploy:
    needs: build_save
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Unzip build artifact
        run: |
          unzip build-artifact.zip
          rm build-artifact.zip

      - name: 'Login via Azure CLI'
        uses: azure/login@v1.5.0
        with:
          creds: ${{ env.AZURE_CREDENTIALS }} # Service Principal credentials saved in GitHub Secrets

      - name: Set Env variables
        uses: Azure/appservice-settings@v1.1.1
        with:
          app-name: ${{env.NAME}}
          app-settings-json: |
            [
                {
                    "name": "WEBSITE_NODE_DEFAULT_VERSION",
                    "value": "~16",
                    "slotSetting": false
                },
                {
                    "name": "DB_HOST",
                    "value": "${{ env.DB_HOST }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_USER",
                    "value": "${{ env.DB_USER }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_PASSWORD",
                    "value": "${{ env.DB_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_NAME",
                    "value": "${{ env.DB_NAME }}",
                    "slotSetting": false
                }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: ${{ env.NAME }}
          respect-funcignore: true
