name: Deploy to Function on Release

on:
  release:
    types: [published]

env:
  NAME: func-tci-services
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DB_HOST: ${{ secrets.TCI_MDB_HOST }}
  DB_USER: ${{ secrets.TCI_MDB_USER }}
  DB_PASSWORD: ${{ secrets.TCI_MDB_PASSWORD }}
  DB_NAME: ${{ secrets.TCI_MDB_NAME }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3.1.0

      - name: 'Setup Node Environment'
        uses: actions/setup-node@v3.5.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 'Prep Npm script for install'
        shell: bash
        run: |
          npm i -g npm
          npm set-script prepare ""
          npm ci --production

      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.6
        with:
          creds: ${{ env.AZURE_CREDENTIALS }} # Service Principal credentials saved in GitHub Secrets

      - name: Set Env variables
        uses: Azure/appservice-settings@v1.1.1
        with:
          app-name: ${{env.NAME}}
          app-settings-json: |
            [
                {
                    "name": "WEBSITE_NODE_DEFAULT_VERSION",
                    "value": "~16",
                    "slotSetting": false
                },
                {
                    "name": "DB_HOST",
                    "value": "${{ env.DB_HOST }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_USER",
                    "value": "${{ env.DB_USER }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_PASSWORD",
                    "value": "${{ env.DB_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_NAME",
                    "value": "${{ env.DB_NAME }}",
                    "slotSetting": false
                }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.4.7
        with:
          app-name: ${{ env.NAME }}
          package: '.'
          respect-funcignore: true
